### ISSUE TITLE
Rename project to Sharktopoda

### ISSUE THREAD

**Issue by hohonuuli** [jaywardell/Sharktopoda#7]
OK, time to start putting the finishing touches on the project. The xcode project and program need to be renamed to Sharktopoda. You can leave the github project name as is though.

**Comment by hohonuuli** [comment]
p.s. Just a reminder that we will likely be open-sourcing the code. Your name is going to be all over the code, so nows probably a good idea to do any final cleanup before other eyeballs start looking over your code 😄

**Comment by jaywardell** [comment]
Regarding open sourcing, there are a couple things I want to let you know about when you're considering open-sourcing.

Licensing:
there are 3 places I use other peoples' code:
- CocoaAsyncSocket for the lowest-level UDP support, marked public domain in the source , but no license info is available at the repo (https://github.com/robbiehanson/CocoaAsyncSocket)
- WeeblyTry to deal with one objective-c style throw from the KVO system, with apparently its own nonstandard license that appears very lenient (
https://github.com/Weebly/Try)
- code for video loading using AVPlayer started out as a copy-paste from a gist by charles boyd
(https://gist.github.com/charlesboyd/e0e840e8af9e52836d51).  It's basically been rewritten aside from some of the error reporting, and his gist lists itself as being licensed by "the unlicensed"

In the case of the first 2, I'm going to try using carthage instead of just having the source sitting in the hierarchy like I did for a "test" project.  Other than that, I'll let you decide how you want to handle this.  I don't see it being a problem to open source a project using this code, but I don't want you blind-sided.

Testing App:
Along the way, I've been using a second project, UDPServerTest, as a testbed first for getting the UDP working, then later to send ump packets to Sharktopoda.  Would you like to have that code as well?  I included a copy in my original bid, but it's changed quite a bit since then.

Finally:
I may want to reference this in my portfolio.  When/if you release it, I trust you'll let me know?

Regarding changing the name of the project: If it doesn't work immediately, I'll probably create a new project and copy everything over.  That's usually what I do when Xcode starts biting my nose, like it sounds like it has for you.

**Comment by hohonuuli** [comment]
> I don't see it being a problem to open source a project using this code, but I don't want you blind-sided.

Thanks for heads up. Consider me forewarned.

> Would you like to have that code as well? [For UDPServerTest]

Yes, that would be great. 

> I may want to reference this in my portfolio. When/if you release it, I trust you'll let me know?

Absolutely!

**Comment by jaywardell** [comment]
okay, project is renamed and working correctly on my side.
problem: somehow the .xcodeproj folder got lost from the repo
investigating...

**Comment by jaywardell** [comment]
No, I think Xcode hosed the repo.

**Comment by hohonuuli** [comment]
Yikes. I'm glad to hear it's not just me who had issues with xcode. Maybe clone the repo to a new directory and replace the relevant files and see if you can push.

**Comment by hohonuuli** [comment]
I'm off line for about an hour. I'll check in then.

**Comment by jaywardell** [comment]
I think I have it fixed in https://github.com/jaywardell/SharktopodaTest/tree/BigRenaming.  Let me know if it works for you, then I'll merge with the main branch if it does.

**Comment by jaywardell** [comment]
Okay, pending your approval, I think this is done.

**Comment by jaywardell** [comment]
okay.  Repository is renamed, only one branch: main, which is the new default.  Let me know if there's anything else to do.
